### ISSUE TITLE
Does not work with forms of the same type

### ISSUE THREAD

**Issue by coldib** [TimBest/django-multi-form-view#3]
I want to implement the following structure:

1. 1 x MasterModel (masterModelType)
2. 2 x DetailModel (detailModelType)

The issue seems that as the fields are named exactly identically, the second form overwrites the first one.

```
form_classes['master_form'] = myApp_forms.SectionForm
form_classes['detail_form1'] = myApp_forms.EntryForm
form_classes['detail_form2'] = myApp_forms.EntryForm

def get_objects(self):
   return {
          'master_form': myApp_models.Section(),
          'detail_form1': myApp_models.Entry(),
          'detail_form2': myApp_models.Entry(),
        }
```

In this case, the data entried in the "last displayed form" is saved twice in the database.

Any ideas how to solve this?

**Comment by TimBest** [comment]
I push out an update to allow for multiple of the same forms. I also added an example of how to accomplish this. If you checkout the demo there is no a profile form that uses to `PhotoForms`. the key is to add a prefix to the forms. Shown here https://github.com/TimBest/django-multi-form-view/blob/master/demo/base/views/profile.py#L24
